export enum FieldArea {
    DefensiveLeft = 'A1',
    DefensiveCenter = 'B1',
    DefensiveRight = 'C1',
    PreDefensiveLeft = 'A2',
    PreDefensiveCenter = 'B2',
    PreDefensiveRight = 'C2',
    MidfieldLeft = 'A3',
    MidfieldCenter = 'B3',
    MidfieldRight = 'C3',
    PreAttackingLeft = 'A4',
    PreAttackingCenter = 'B4',
    PreAttackingRight = 'C4',
    AttackingLeft = 'A5',
    AttackingCenter = 'B5',
    AttackingRight = 'C5',
}
